CUDA_VISIBLE_DEVCES=0 python train_fomile.py --Transformation TPS --FeatureExtraction ResNet --SequenceModeling BiLSTM --Prediction Attn \
	--experiment_name /FOMILE/CEL_CE/ \
	--src_train_data /data/hungtt/KLTN/SMILE/data_lmdb_release/training \
	--src_select_data MJ-ST \
	--src_batch_ratio 0.5-0.5 \
	--tar_train_data /data/hungtt/KLTN/SMILE/data_lmdb_release/validation \
	--tar_select_data real_data \
	--tar_batch_ratio 1.0 \
	--valid_data /data/hungtt/KLTN/SMILE/data_lmdb_release/evaluation/IC15_1811 \
	--batch_size 64 --lr 1 \
	--workers 16 \
	--num_iter 30000 \
	--continue_model pretrained/pretrained.pth \
	--init_portion 0.0 --add_portion 0.00005 \
	--loss_type CELoss --entropy_type CE \
	--src_lambda 1.0 --tar_lambda 1.0 \
	--focal_alpha 0.2 --focal_gamma 2 --loss_focal_gamma 2 \
	--data_filtering_off
